### ISSUE TITLE
State file is missing 

### ISSUE THREAD

**Issue by mohamedbrahem** [GtheSheep/tap-pinterest-ads#11]
I want to add a state file to the current project to pull the data from a given date in that state file 
Any ideas how can I implement that ?

**Comment by GtheSheep** [comment]
Hey, yeah you should just be able to create a JSON file using the args in the README.me, 'start_date' controls the date from which ad/ account analytics are collected, unless you're referring to also having an end date rather than it defaulting you yesterday?

**Comment by mohamedbrahem** [comment]
I want to read the start_date **from the State.json file** instead of the config.json file and the command option --state and pass state.json file. is that possible or I need to update the streams.py implementation?

**Comment by mohamedbrahem** [comment]
For example here's my state file : 

`{
  "bookmarks": {
    "ad_analytics": {
      "start_date": "2022-04-04T00:00:00Z"
    }
  }
}`

I want to point the script to read from the state.json file instead of the config.json, otherwise how can I make use of the command option --state, tried that but probably didn't read the state file. maybe I have an issue in my state file json structure or formatting.

Thanks in advances.

**Comment by mohamedbrahem** [comment]
Maybe it's possible to override in under class TapPinterestAds(Tap) the function def load_state and pass the state file ?

**Comment by GtheSheep** [comment]
Ahh sorry I misread the initial question, are you running the tap directly or via meltano? Im pretty sure the 'get_starting_timestamp' function in the analytics part of 'streams.py' should only default to what's in the config.Json when there's nothing in the context (loaded from the state file).
I think the state may be partitioned by 'ad_id' and 'account_id' in their respective streams so you may need to update the format of your state file to respect that for it to load into context correctly?

**Comment by GtheSheep** [comment]
I.e. something like:

{ "bookmarks": { "ad_analytics": [{ "start_date": "2022-04-04T00:00:00Z", "ad_id": <some ad id>}, {...}]} }

**Comment by mohamedbrahem** [comment]
Thanks for your quick answer, perhaps I've created a state file with this context : 
`{
  "bookmarks": {
    "ad_analytics": 
      {
        "ad_account_id": "549757129026",
        "DATE": "2022-04-04T00:00:00Z",
        "AD_ID": "687205663901"
      }
  }
}`
but it's not working as expected and not reading the date from the state file.

**Comment by mohamedbrahem** [comment]
Maybe the structure of the State file I wrote is wrong or missing something?

**Comment by GtheSheep** [comment]
could just run the tap as of yesterday to create a dummy state you can edit?
for ref, mine is of the format:
```
{"bookmarks": 
     "ad_analytics": {
         "partitions": [
             {"context": {"ad_id": "1234567890987654321"}, "replication_key": "DATE", "replication_key_value": "2022-04-17T00:00:00Z"}
         ]
     }
}
```
