### ISSUE TITLE
python version 3.10 required

### ISSUE THREAD

**Issue by denniskeends** [GtheSheep/tap-pinterest-ads#7]
I'm trying to add this to a new poetry project and I've run into an issue. I think the version dependencies are backwards, resulting in the wrong version of python being required.

context:

this is what's in the pyproject.toml `python = "<3.10,>=3.6.2"`

```
The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - tap-pinterest-ads requires Python <3.10,>=3.6.2, so it will not be satisfied for Python >=3.10,<4.0

  Because worker-singer-kegerator depends on tap-pinterest-ads (rev main) which requires Python <3.10,>=3.6.2, version solving failed.

For tap-pinterest-ads, a possible solution would be to set the `python` property to ">=3.8,<3.10"
```

pr here : https://github.com/GtheSheep/tap-pinterest-ads/pull/8

**Comment by GtheSheep** [comment]
Hey, thanks for checking this out! It looks as though the version of Python you're using is between 3.8 and 4, whereas 3.6 is the max tested by this project from the SDK, could you try bumping the poetry conditions to 3.10 and something above your current python version and see if this works?
Or please let me know your Python version and I'll give it a shot tomorrow 😁
Thanks

**Comment by GtheSheep** [comment]
```
python = "<=3.10,>=3.6.2"
```
Will probs do it, will test shortly

**Comment by denniskeends** [comment]
I'm using 3.8.3 and I used this with pip previously and it seemed to be good on that version.

**Comment by GtheSheep** [comment]
ahh I see, so there were some non-overlapping versions it wasn't satisfying? are you all good or would you like me to test it on a higher Python version to see if I can bump the version in this project?

**Comment by denniskeends** [comment]
My assumption was that if I used `^3.8` then poetry would handle the rest, or that's how I read the docs. As it turns out my target isn't compatible anyways. So I'm all good.

**Comment by GtheSheep** [comment]
👌 cool, thanks! hope this works for you in the end somehow! 😸
